# Generated by Django 3.1.7 on 2021-06-30 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_auto_20210408_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='users.account')),
                ('users', models.ManyToManyField(null=True, related_name='teams_users', to='users.Account')),
            ],
            options={
                'unique_together': {('title', 'creator')},
            },
        ),
    ]
