# Generated by Django 3.0.8 on 2020-12-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
