# Generated by Django 3.0.8 on 2020-12-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('users', '0002_auto_20201203_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
