# Generated by Django 3.0.8 on 2020-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('users', '0003_auto_20201203_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
