# Generated by Django 3.0.8 on 2020-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201203_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='district_string',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='region_string',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
