# Generated by Django 3.0.8 on 2021-01-29 11:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210129_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appentrances',
            name='device_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
