# Generated by Django 3.0.8 on 2021-01-29 11:24

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210129_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appentrances',
            name='device_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
