# Generated by Django 3.0.8 on 2021-02-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['user__created_at']},
        ),
    ]
