# Generated by Django 3.0.8 on 2021-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210209_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=None, max_length=32),
        ),
    ]
