# Generated by Django 3.1.7 on 2021-03-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20210209_1427'),
        ('floors', '0003_auto_20210219_1255'),
        ('users', '0009_auto_20210224_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficePanelRelation',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('access_code', models.IntegerField(max_length=11, unique=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_panels', to='users.account')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_panels', to='floors.floor')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_panels', to='offices.office')),
            ],
        ),
    ]
