# Generated by Django 3.1.7 on 2021-04-06 08:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210326_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appentrances',
            name='device_info',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='officepanelrelation',
            name='access_code',
            field=models.IntegerField(unique=True),
        ),
    ]
