# Generated by Django 3.1.7 on 2021-05-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210220_0903'),
        ('users', '0012_auto_20210408_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='officepanelrelation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_panels', to='rooms.room'),
        ),
    ]
