# Generated by Django 3.1 on 2021-08-12 12:24

from django.db import migrations


def add_roles(apps, schema_editor):
    Role = apps.get_model('movies', 'Role')
    role_titles = ['Actor', 'Writer', 'Director']
    roles = []
    for title in role_titles:
        roles.append(Role(title=title))
    Role.objects.bulk_create(roles)


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_roles),
    ]
