# Generated by Django 3.0.8 on 2020-10-15 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0002_auto_20201015_1238'),
        ('files', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='files.File'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_bookable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='room_types.RoomType'),
        ),
        migrations.AddField(
            model_name='room',
            name='seats_available',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RoomMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=64)),
                ('x', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
        ),
    ]
