# Generated by Django 3.0.8 on 2020-11-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('offices', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='offices.OfficeZone'),
        ),
    ]
