# Generated by Django 3.0.8 on 2021-02-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210209_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor__title', 'title']},
        ),
    ]
