# Generated by Django 3.0.8 on 2020-12-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_bookable',
        ),
    ]
