# Generated by Django 3.1.7 on 2021-05-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0003_auto_20210219_1255'),
        ('rooms', '0003_auto_20210220_0903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('title', 'floor')},
        ),
    ]
