options:
  docker: true

clone:
  depth: full

definitions:
  steps:
    - step: &Build
        name: Create Docker image
        image: python:3.8
        caches:
          - docker
          - pip
        script:
          - export PYTHONPATH=$PYTHONPATH:$PWD
          - export DOCKER_CLIENT_TIMEOUT=120
          - export COMPOSE_HTTP_TIMEOUT=120
          - export BITBUCKET_PROJECT_KEY="${BITBUCKET_PROJECT_KEY,,}"
          - docker login $DOCKER_REG -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker build -t $DOCKER_REG/$BITBUCKET_PROJECT_KEY/$BITBUCKET_BRANCH/$BITBUCKET_REPO_SLUG:latest -f Dockerfile .
          - docker push $DOCKER_REG/$BITBUCKET_PROJECT_KEY/$BITBUCKET_BRANCH/$BITBUCKET_REPO_SLUG:latest

    - step: &Deploy
        name: Restart compose network
        script:
          - pipe: atlassian/trigger-pipeline:4.2.1
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              REPOSITORY: 'simpleoffice-deploy'
              CUSTOM_PIPELINE_NAME: $DEPLOYMENT
              WAIT: 'true'
    
    - step: &obfuscate_and_deploy_code_to_repo
          name: Compile for avito TEST
          image: python:3.8
          script:
            - pip install --user -r requirements.txt
            - pip install pyarmor
            - pyarmor obfuscate --src="." --exclude venv -r --output=/var/distribute manage.py
            - find . -name '*.py' -type f -delete
            - rm -f booking_api_django_new/environments/*
            - rm -f bitbucket-pipelines.yml
            - cp -rf . /var/distribute
            - git clone https://${BITBUCKET_USERNAME}:${APP_SECRET}@bitbucket.org/liis_software/${REPO_NAME}.git
            - git config --global user.email "you@example.com"
            - git config --global user.name "avito_update"
            - cd ${REPO_NAME}
            - rm -rf ./*
            - mv /var/distribute/* ./
            - git add . && git commit -m 'Update' && git push

    - step: &Compile
          name: Compile
          image: python:3.8
          script:
            - pip install --user -r requirements.txt
            - pip install pyarmor
            - pyarmor obfuscate --src="." --exclude venv -r --output=/var/distribute manage.py
            - find . -name '*.py' -type f -delete
            - cp -rf . /var/distribute
            - tar -cvf api-test.tar /var/distribute
            - pipe: atlassian/bitbucket-upload-file:0.1.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "api-test.tar"

pipelines:
  branches:
    compile:
      - step: *Compile

    simple-office/prod:
      - step:
          <<: *Build

    simple-office/prod-deploy:
      - step:
          <<: *Deploy
          deployment: simple-office-liis-su
    
    simple-office/dev:
      - step:
          <<: *Build
      - step:
          <<: *Deploy
          deployment: dev-simple-office-liis-su

  custom:
    AVITO-obfuscate_and_deploy_code_to_Avito_repo:
      - step: 
          <<: *obfuscate_and_deploy_code_to_repo
          deployment: Avito