options:
  docker: true

clone:
  depth: full

definitions:
  steps:
    - step: &Build
        name: Create Docker image
        image: python:3.8
        caches:
          - docker
          - pip
        script:
          - export PYTHONPATH=$PYTHONPATH:$PWD
          - export DOCKER_CLIENT_TIMEOUT=120
          - export COMPOSE_HTTP_TIMEOUT=120
          - export BITBUCKET_PROJECT_KEY="${BITBUCKET_PROJECT_KEY,,}"
          - docker login $DOCKER_REG -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker build -t $DOCKER_REG/$BITBUCKET_PROJECT_KEY/$BITBUCKET_BRANCH/$BITBUCKET_REPO_SLUG:latest -f Dockerfile .
          - docker push $DOCKER_REG/$BITBUCKET_PROJECT_KEY/$BITBUCKET_BRANCH/$BITBUCKET_REPO_SLUG:latest

    - step: &Deploy
        name: Restart compose network
        script:
          - pipe: atlassian/trigger-pipeline:4.2.1
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              REPOSITORY: 'simpleoffice-deploy'
              BRANCH_NAME: 'develop_instans'
              CUSTOM_PIPELINE_NAME: $DEPLOYMENT
              WAIT: 'true'

pipelines:
  branches:
    feature/so_lahta_panel:
      - step:
          <<: *Build
      - step:
          <<: *Deploy
          deployment: dev-simple-office-lahta