version : '3.8'

volumes:
  postgres_data:


services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./static:/var/www/movie/static
    depends_on:
      - backend
    ports:
      - "80:80"

  pg-database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/project/static
    tty: true
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pg-database


