# Generated by Django 3.0.8 on 2021-01-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('push_tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='users.Account'),
        ),
    ]
