# Generated by Django 3.1.7 on 2021-07-20 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paid_until',
            field=models.DateField(default=datetime.date(2021, 7, 25)),
        ),
    ]
