# Generated by Django 3.1.7 on 2021-07-26 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(default=datetime.date(2021, 7, 31)),
        ),
    ]
