# Generated by Django 3.1.7 on 2021-08-06 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210726_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(default=datetime.date(2021, 8, 11)),
        ),
    ]
