# Generated by Django 3.0.8 on 2020-10-15 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='account',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='tables', to='files.File'),
        ),
    ]
