# Generated by Django 3.0.8 on 2021-02-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_tablemarker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemarker',
            name='icon',
        ),
    ]
