# Generated by Django 3.1.7 on 2021-05-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20210209_1427'),
        ('tables', '0003_auto_20210220_0903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tabletag',
            unique_together={('title', 'office')},
        ),
    ]
