# Generated by Django 3.0.8 on 2021-01-11 10:57

from django.db import migrations, models
import groups.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('access', models.IntegerField(default=4, validators=[groups.models.integer_validator])),
                ('is_deletable', models.BooleanField(default=True)),
            ],
        ),
    ]
