# Generated by Django 3.0.8 on 2021-01-11 10:57

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('color', models.CharField(default='#0079c1', max_length=8)),
                ('bookable', models.BooleanField(default=False)),
                ('work_interval_days', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(0)])),
                ('work_interval_hours', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('unified', models.BooleanField(default=False)),
                ('is_deletable', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtypes', to='offices.Office')),
            ],
        ),
    ]
