# Generated by Django 3.0.8 on 2020-11-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officezone',
            name='title',
            field=models.CharField(default='Зона коворкинга', max_length=256),
        ),
    ]
