# Generated by Django 3.0.8 on 2021-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20210201_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='office',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
