# Generated by Django 3.1.7 on 2021-07-26 12:08

from django.db import migrations, models
import offices.models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_auto_20210601_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=128, validators=[offices.models.timezone_validator]),
        ),
    ]
