# Generated by Django 3.0.8 on 2021-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('active', 'active'), ('canceled', 'canceled'), ('auto_canceled', 'auto_canceled')], default='waiting', max_length=20),
        ),
    ]
