# Generated by Django 3.0.8 on 2020-11-17 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('users', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
    ]
