# Generated by Django 3.0.8 on 2021-02-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('active', 'active'), ('canceled', 'canceled'), ('auto_canceled', 'auto_canceled'), ('over', 'over')], default='waiting', max_length=20),
        ),
    ]
