# Generated by Django 3.1.7 on 2021-06-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_bookings', '0001_initial'),
        ('bookings', '0004_jobstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_booking_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group_bookings.groupbooking'),
        ),
    ]
