# Generated by Django 3.1.7 on 2021-06-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_group_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='group_booking_id',
            new_name='group_booking',
        ),
    ]
