# Generated by Django 3.1.7 on 2021-06-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_bookings', '0001_initial'),
        ('bookings', '0006_auto_20210629_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='group_booking',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='group_bookings.groupbooking'),
        ),
    ]
