# Generated by Django 3.1.7 on 2021-06-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_bookings', '0001_initial'),
        ('bookings', '0008_auto_20210630_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='group_booking',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='group_bookings.groupbooking'),
        ),
    ]
