# Generated by Django 3.0.8 on 2021-01-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20210129_1344'),
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('title', 'office')},
        ),
    ]
