# Generated by Django 3.0.8 on 2020-10-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floormap',
            name='height',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='width',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
