# Generated by Django 3.0.8 on 2021-02-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0002_auto_20210201_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floormap',
            name='floor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='floors.Floor'),
        ),
    ]
